services:
  - type: web
    name: hellomcdo-bot
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
